BN6chips = 
	{"Standard":
	  {
		"Name": "Cannon",
		"Element": "Null",
		"MB": "6 MB",
		"ATK": "40",
		"Codes": "A B C *",
		"Description": "Cannon to attack 1 enemy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/36/BN6Chip001.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HiCannon",
		"Element": "Null",
		"MB": "24 MB",
		"ATK": "100",
		"Codes": "L M N",
		"Description": "Cannon to attack 1 enemy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/7/73/BN6Chip002.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "M-Cannon",
		"Element": "Null",
		"MB": "38 MB",
		"ATK": "180",
		"Codes": "R S T *",
		"Description": "Cannon to attack 1 enemy",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/89/BN6Chip003.png",
		"MoreDetails": "",
		"Alias": "MCannon"
	  },
	  {
		"Name": "AirShot",
		"Element": "Wind",
		"MB": "4 MB",
		"ATK": "20",
		"Codes": "*",
		"Description": "Knock enmy back 1 square",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/83/BN6Chip004.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Vulcan1",
		"Element": "Null",
		"MB": "5 MB",
		"ATK": "10",
		"Codes": "B D S *",
		"Description": "3-shot to pierce 1 panel!",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/e4/BN6Chip005.png",
		"MoreDetails": "https://bit.ly/2IxfRET",
	  },
	  {
		"Name": "Vulcan2",
		"Element": "Null",
		"MB": "18 MB",
		"ATK": "15",
		"Codes": "D F L",
		"Description": "4-shot to pierce 1 panel!",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/9/98/BN6Chip006.png",
		"MoreDetails": "https://bit.ly/2IxfRET",
	  },
	  {
		"Name": "Vulcan3",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "20",
		"Codes": "A G R",
		"Description": "5-shot to pierce 1 panel!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/e/e2/BN6Chip007.png",
		"MoreDetails": "https://bit.ly/2IxfRET",
	  },
	  {
		"Name": "SuprVulc",
		"Element": "Null",
		"MB": "75 MB",
		"ATK": "20",
		"Codes": "V",
		"Description": "10-shot Vulcan Cannon!",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/9/90/BN6Chip008.png",
		"MoreDetails": "https://bit.ly/2IxfRET",
		"Alias": "SuperVulcan,Super Vulcan"
	  },
	  {
		"Name": "Spreadr1",
		"Element": "Null",
		"MB": "10 MB",
		"ATK": "30",
		"Codes": "L M N *",
		"Description": "Spreads damg to adj panels",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/fe/BN6Chip009.png",
		"MoreDetails": "",
		"Alias": "Spreader1"
	  },
	  {
		"Name": "Spreadr2",
		"Element": "Null",
		"MB": "18 MB",
		"ATK": "60",
		"Codes": "A B C *",
		"Description": "Spreads damg to adj panels",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/d/df/BN6Chip010.png",
		"MoreDetails": "",
		"Alias": "Spreader2"
	  },
	  {
		"Name": "Spreadr3",
		"Element": "Null",
		"MB": "26 MB",
		"ATK": "90",
		"Codes": "Q R S *",
		"Description": "Spreads damg to adj panels",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/c/c2/BN6Chip011.png",
		"MoreDetails": "",
		"Alias": "Spreader3"
	  },
	  {
		"Name": "TankCan1",
		"Element": "Null",
		"MB": "17 MB",
		"ATK": "120",
		"Codes": "A G R",
		"Description": "3sqr blst if hits end row",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/15/BN6Chip012.png",
		"MoreDetails": "",
		"Alias": "TankCannon1"
	  },
	  {
		"Name": "TankCan2",
		"Element": "Null",
		"MB": "28 MB",
		"ATK": "160",
		"Codes": "L S V",
		"Description": "3sqr blst if hits end row",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/8/88/BN6Chip013.png",
		"MoreDetails": "",
		"Alias": "TankCannon2"
	  },
	  {
		"Name": "TankCan3",
		"Element": "Null",
		"MB": "39 MB",
		"ATK": "200",
		"Codes": "B M P",
		"Description": "3sqr blst if hits end row",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/e5/BN6Chip014.png",
		"MoreDetails": "",
		"Alias": "TankCannon3"
	  },
	  {
		"Name": "GunDelS1",
		"Element": "Null",
		"MB": "15 MB",
		"ATK": "0",
		"Codes": "C M T *",
		"Description": "Hits row 2pnl ahd w/sunshne",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/2/26/BN6Chip015.png",
		"MoreDetails": "https://bit.ly/2VXrpEL",
		"Alias": "GunDelSol1"
	  },
	  {
		"Name": "GunDelSl2",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "0",
		"Codes": "B E R",
		"Description": "Hits row 2pnl ahd w/sunshne",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/2a/BN6Chip016.png",
		"MoreDetails": "https://bit.ly/2VXrpEL",
		"Alias": "GunDelSol2"
	  },
	  {
		"Name": "GunDelS3",
		"Element": "Null",
		"MB": "38 MB",
		"ATK": "0",
		"Codes": "N Q W",
		"Description": "Hits row 2pnl ahd w/sunshne",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/0/0e/BN6Chip017.png",
		"MoreDetails": "https://bit.ly/2VXrpEL",
		"Alias": "GunDelSol3"
	  },
	  {
		"Name": "YoYo",
		"Element": "Null",
		"MB": "32 MB",
		"ATK": "50",
		"Codes": "L M N *",
		"Description": "YoYo atk reaches 3sq ahead",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/67/BN6Chip018.png",
		"MoreDetails": "https://bit.ly/2Gws0qu",
	  },
	  {
		"Name": "FireBrn1",
		"Element": "Fire",
		"MB": "8 MB",
		"ATK": "70",
		"Codes": "F G H *",
		"Description": "Crcks 3 sqrs ahd with fire",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b7/BN6Chip019.png",
		"MoreDetails": "",
		"Alias": "FireBurn1"
	  },
	  {
		"Name": "FireBrn2",
		"Element": "Fire",
		"MB": "21 MB",
		"ATK": "110",
		"Codes": "S T U",
		"Description": "Crcks 3 sqrs ahd with fire",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/21/BN6Chip020.png",
		"MoreDetails": "",
		"Alias": "FireBurn2"
	  },
	  {
		"Name": "FireBrn3",
		"Element": "Fire",
		"MB": "34 MB",
		"ATK": "150",
		"Codes": "C D E",
		"Description": "Crcks 3 sqrs ahd with fire",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/c/c1/BN6Chip021.png",
		"MoreDetails": "",
		"Alias": "FireBurn3"
	  },
	  {
		"Name": "WideSht",
		"Element": "Aqua",
		"MB": "34 MB",
		"ATK": "100",
		"Codes": "P Q R",
		"Description": "Fires 3sq shotgun blast!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/ee/BN6Chip022.png",
		"MoreDetails": "",
		"Alias": "FireBurn3"
	  },
	  {
		"Name": "TrnArrw1",
		"Element": "Aqua",
		"MB": "30 MB",
		"ATK": "30",
		"Codes": "A F K",
		"Description": "Hits enmy w/ arrow use dstnc",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/d/d1/BN6Chip023.png",
		"MoreDetails": "https://bit.ly/2Dpy6Id",
		"Alias": "TrainArrow1,TurnArrow1"
	  },
	  {
		"Name": "TrnArrw2",
		"Element": "Aqua",
		"MB": "36 MB",
		"ATK": "40",
		"Codes": "G M Z",
		"Description": "Hits enmy w/ arrow. Use dstnc",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/3/31/BN6Chip024.png",
		"MoreDetails": "https://bit.ly/2Dpy6Id",
		"Alias": "TrainArrow2,TurnArrow2"
	  },
	  {
		"Name": "TrnArrw3",
		"Element": "Aqua",
		"MB": "42 MB",
		"ATK": "50",
		"Codes": "M S Y",
		"Description": "Hits enmy w/arrow. Use dstnc",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/c/c5/BN6Chip025.png",
		"MoreDetails": "https://bit.ly/2Dpy6Id",
		"Alias": "TrainArrow3,TurnArrow3"
	  },
	  {
		"Name": "BblStar1",
		"Element": "Aqua",
		"MB": "30 MB",
		"ATK": "60",
		"Codes": "B E T",
		"Description": "Seals an enemy in a bubble.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/8c/BN6Chip026.png",
		"MoreDetails": "",
		"Alias": "BubbleStar1"
	  },
	  {
		"Name": "BblStar2",
		"Element": "Aqua",
		"MB": "38 MB",
		"ATK": "80",
		"Codes": "C L V",
		"Description": "Seals an enemy in a bubble.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/5/5e/BN6Chip027.png",
		"MoreDetails": "",
		"Alias": "BubbleStar2"
	  },
	  {
		"Name": "BblStar3",
		"Element": "Aqua",
		"MB": "46 MB",
		"ATK": "100",
		"Codes": "G R S",
		"Description": "Seals an enemy in a bubble.",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/0/0f/BN6Chip028.png",
		"MoreDetails": "",
		"Alias": "BubbleStar3"
	  },
	  {
		"Name": "Thunder",
		"Element": "Elec",
		"MB": "7 MB",
		"ATK": "40",
		"Codes": "B R S *",
		"Description": "Pralyzing electric attack!",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/f/f5/BN6Chip029.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DolThdr1",
		"Element": "Elec",
		"MB": "24 MB",
		"ATK": "120",
		"Codes": "A E Q",
		"Description": "A piercng thunder attack!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/d/de/BN6Chip030.png",
		"MoreDetails": "",
		"Alias": "DolThunder1"
	  },
	  {
		"Name": "DolThdr2",
		"Element": "Elec",
		"MB": "31 MB",
		"ATK": "150",
		"Codes": "C L P",
		"Description": "A piercng thunder attack!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/6d/BN6Chip031.png",
		"MoreDetails": "",
		"Alias": "DolThunder2"
	  },
	  {
		"Name": "DolThdr3",
		"Element": "Elec",
		"MB": "38 MB",
		"ATK": "180",
		"Codes": "B R V",
		"Description": "A piercng thunder attack!",
		"Image": "",
		"MoreDetails": "https://vignette2.wikia.nocookie.net/megaman/images/5/5f/BN6Chip032.png",
		"Alias": "DolThunder3"
	  },
	  {
		"Name": "ElcPuls1",
		"Element": "Elec",
		"MB": "32 MB",
		"ATK": "100",
		"Codes": "J L S",
		"Description": "Sprd elec puls that paralyzes",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/6/6d/BN6Chip033.png",
		"MoreDetails": "https://bit.ly/2Du6q53",
		"Alias": "ElecPulse1,ElecPuls1"
	  },
	  {
		"Name": "ElcPuls2",
		"Element": "Elec",
		"MB": "36 MB",
		"ATK": "120",
		"Codes": "A E J",
		"Description": "Sprd elec pulse. Pul enemy in.",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/bc/BN6Chip034.png",
		"MoreDetails": "https://bit.ly/2Du6q53",
		"Alias": "ElecPulse2,ElecPuls2"
	  },
	  {
		"Name": "ElcPuls3",
		"Element": "Elec",
		"MB": "40 MB",
		"ATK": "140",
		"Codes": "A J S",
		"Description": "Sprd elec puls. Hit w/HP bug.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/13/BN6Chip035.png",
		"MoreDetails": "https://bit.ly/2Du6q53",
		"Alias": "ElecPulse3,ElecPuls3"
	  },
	  {
		"Name": "CornSht1",
		"Element": "Wood",
		"MB": "14 MB",
		"ATK": "50",
		"Codes": "J K L",
		"Description": "Damages enemies w/corn",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/a9/BN6Chip036.png",
		"MoreDetails": "https://bit.ly/2W30Az2",
		"Alias": "CornShot1"
	  },
	  {
		"Name": "CornSht2",
		"Element": "Wood",
		"MB": "26 MB",
		"ATK": "60",
		"Codes": "C D E",
		"Description": "Damages enemies w/corn",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/0/0d/BN6Chip037.png",
		"MoreDetails": "https://bit.ly/2W30Az2",
		"Alias": "CornShot2"
	  },
	  {
		"Name": "CornSht3",
		"Element": "Wood",
		"MB": "38 MB",
		"ATK": "70",
		"Codes": "P Q R",
		"Description": "Damages enemies w/corn",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/5/53/BN6Chip038.png",
		"MoreDetails": "https://bit.ly/2W30Az2",
		"Alias": "CornShot3"
	  },
	  {
		"Name": "RskyHny1",
		"Element": "Wood",
		"MB": "21 MB",
		"ATK": "10",
		"Codes": "B G S",
		"Description": "Bees attk whle hive defending.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/c/c3/BN6Chip039.png",
		"MoreDetails": "https://bit.ly/2IvIEr2",
		"Alias": "RiskyHoney1, RskyHoney1"
	  },
	  {
		"Name": "RskyHny2",
		"Element": "Wood",
		"MB": "28 MB",
		"ATK": "15",
		"Codes": "C R V",
		"Description": "Bees attk whle hive defending",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/4/49/BN6Chip040.png",
		"MoreDetails": "https://bit.ly/2IvIEr2",
		"Alias": "RiskyHoney2, RskyHoney2"
	  },
	  {
		"Name": "RskyHny3",
		"Element": "Wood",
		"MB": "35 MB",
		"ATK": "20",
		"Codes": "A D M",
		"Description": "Bees attk whle hive defending",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/e3/BN6Chip041.png",
		"MoreDetails": "https://bit.ly/2IvIEr2",
		"Alias": "RiskyHoney3, RskyHoney3"
	  },
	  {
		"Name": "RlngLog1",
		"Element": "Wood",
		"MB": "14 MB",
		"ATK": "50",
		"Codes": "I K P",
		"Description": "Send out 2 logs 2pnl fwd",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/3/39/BN6Chip042.png",
		"MoreDetails": "https://bit.ly/31T62rm",
		"Alias": "RollingLog1, RollLog1"
	  },
	  {
		"Name": "RlngLog2",
		"Element": "Wood",
		"MB": "26 MB",
		"ATK": "70",
		"Codes": "E Q Z",
		"Description": "Send out 2 logs 2pnl fwd",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/f/f1/BN6Chip043.png",
		"MoreDetails": "https://bit.ly/31T62rm",
		"Alias": "RollingLog2, RollLog2"
	  },
	  {
		"Name": "RlngLog3",
		"Element": "Wood",
		"MB": "35 MB",
		"ATK": "90",
		"Codes": "F N W",
		"Description": "Send out 2 logs 2pnl fwd",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/17/BN6Chip044.png",
		"MoreDetails": "https://bit.ly/31T62rm",
		"Alias": "RollingLog3, RollLog3"
	  },
	  {
		"Name": "IronShl1",
		"Element": "Break",
		"MB": "13 MB",
		"ATK": "70",
		"Codes": "J K L",
		"Description": "Fire off piercing shell.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/7/79/BN6Chip045.png",
		"MoreDetails": "https://bit.ly/2XQZ3jB",
		"Alias": "IronShell1, Iron Shell 1"
	  },
	  {
		"Name": "IronShl2",
		"Element": "Break",
		"MB": "20 MB",
		"ATK": "100",
		"Codes": "C D E",
		"Description": "Fire off piercing shell.",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/fc/BN6Chip046.png",
		"MoreDetails": "https://bit.ly/2XQZ3jB",
		"Alias": "IronShell2, Iron Shell 2"
	  },
	  {
		"Name": "IronShl3",
		"Element": "Break",
		"MB": "27 MB",
		"ATK": "130",
		"Codes": "L M N",
		"Description": "Fire off piercing shell.",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/ee/BN6Chip047.png",
		"MoreDetails": "https://bit.ly/2XQZ3jB",
		"Alias": "IronShell3, Iron Shell 3"
	  },
	  {
		"Name": "AuraHed1",
		"Element": "Break",
		"MB": "25 MB",
		"ATK": "130",
		"Codes": "B C D",
		"Description": "A flying head with 2spc tail",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/d/d2/BN6Chip048.png",
		"MoreDetails": "https://bit.ly/30ewUQQ",
		"Alias": "AuraHead1"
	  },
	  {
		"Name": "AuraHed2",
		"Element": "Break",
		"MB": "33 MB",
		"ATK": "150",
		"Codes": "D E F",
		"Description": "A flying head with 2spc tail",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/c/ce/BN6Chip049.png",
		"MoreDetails": "https://bit.ly/30ewUQQ",
		"Alias": "AuraHead2"
	  },
	  {
		"Name": "AuraHed3",
		"Element": "Break",
		"MB": "39 MB",
		"ATK": "170",
		"Codes": "F G H",
		"Description": "A flying head with 2spc tail",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/5/54/BN6Chip050.png",
		"MoreDetails": "https://bit.ly/30ewUQQ",
		"Alias": "AuraHead3"
	  },
	  {
		"Name": "AirHocky",
		"Element": "Break",
		"MB": "19 MB",
		"ATK": "60",
		"Codes": "L M N",
		"Description": "Bounce the puck off walls",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/9/90/BN6Chip051.png",
		"MoreDetails": "https://bit.ly/2G05ZRn",
		"Alias": "AirHockey"
	  },
	  {
		"Name": "DrilArm",
		"Element": "Break",
		"MB": "32 MB",
		"ATK": "70",
		"Codes": "G M W",
		"Description": "Knocks enmy 2sq away",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/7/7d/BN6Chip052.png",
		"MoreDetails": "https://bit.ly/2JkHpwE",
	  },
	  {
		"Name": "Tornado",
		"Element": "Wind",
		"MB": "16 MB",
		"ATK": "20",
		"Codes": "L R T",
		"Description": "8hit strm 2 squares ahead",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/3/34/BN6Chip053.png",
		"MoreDetails": "https://bit.ly/2XOLMYW",
	  },
	  {
		"Name": "Static",
		"Element": "Wind",
		"MB": "30 MB",
		"ATK": "20",
		"Codes": "G S V",
		"Description": "A static blast 2sq ahead",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2d/BN6Chip054.png",
		"MoreDetails": "https://bit.ly/30ifz9Q",
	  },
	  {
		"Name": "MachGun1",
		"Element": "Cursor",
		"MB": "12 MB",
		"ATK": "30",
		"Codes": "A R T *",
		"Description": "Fire 9sts at row w/clst enmy",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/10/BN6Chip055.png",
		"MoreDetails": "https://bit.ly/30fLFmH",
		"Alias": "MachineGun1"
	  },
	  {
		"Name": "MachGun2",
		"Element": "Cursor",
		"MB": "24 MB",
		"ATK": "50",
		"Codes": "E G S",
		"Description": "Fire 9sts at row w/clst enmy",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/1e/BN6Chip056.png",
		"MoreDetails": "https://bit.ly/30fLFmH",
		"Alias": "MachineGun2"
	  },
	  {
		"Name": "MachGun3",
		"Element": "Cursor",
		"MB": "36 MB",
		"ATK": "70",
		"Codes": "B F M",
		"Description": "Fire 9sts at row w/clst enmy",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a1/BN6Chip057.png",
		"MoreDetails": "https://bit.ly/30fLFmH",
		"Alias": "MachineGun3"
	  },
	  {
		"Name": "MiniBomb",
		"Element": "Null",
		"MB": "6 MB",
		"ATK": "50",
		"Codes": "B L R *",
		"Description": "Throws a MiniBomb 3sq ahead",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/1/12/BN6Chip058.png",
		"MoreDetails": "https://bit.ly/2S0wbzW",
	  },
	  {
		"Name": "BigBomb",
		"Element": "Null",
		"MB": "32 MB",
		"ATK": "140",
		"Codes": "O P V",
		"Description": "Throws a 9 panl bomb 3panl fwd",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/e/e7/BN6Chip059.png",
		"MoreDetails": "https://bit.ly/2S0wbzW",
	  },
	  {
		"Name": "EnergBom",
		"Element": "Null",
		"MB": "11 MB",
		"ATK": "40",
		"Codes": "C K V *",
		"Description": "Throws a bomb 3sq ahead",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/5/57/BN6Chip060.png",
		"MoreDetails": "https://bit.ly/2xzd6vp",
		"Alias": "EnergyBomb"
	  },
	  {
		"Name": "MegEnBom",
		"Element": "Null",
		"MB": "27 MB",
		"ATK": "60",
		"Codes": "G M O *",
		"Description": "Throws a bomb 3sq ahead",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/9/96/BN6Chip061.png",
		"MoreDetails": "https://bit.ly/2xzd6vp",
		"Alias": "MegaEnergyBomb, MegEnergyBomb"
	  },
	  {
		"Name": "FlshBom1",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "40",
		"Codes": "J Q L *",
		"Description": "Thrw dlyd stun bomb 3sq fwd",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/7/78/BN6Chip062.png",
		"MoreDetails": "https://bit.ly/2L9dk5g",
		"Alias": "FlashBomb1, FlashBom1"
	  },
	  {
		"Name": "FlshBom2",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "40",
		"Codes": "G K R",
		"Description": "Thrw dlyd stun bomb 3sq fwd",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/e/eb/BN6Chip063.png",
		"MoreDetails": "https://bit.ly/2L9dk5g",
		"Alias": "FlashBomb2, FlashBom2"
	  },
	  {
		"Name": "FlshBom3",
		"Element": "Null",
		"MB": "38 MB",
		"ATK": "100",
		"Codes": "H P S",
		"Description": "Thrw dlyd stun bomb 3sq fwd",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/8a/BN6Chip064.png",
		"MoreDetails": "https://bit.ly/2L9dk5g",
		"Alias": "FlashBomb3, FlashBom3"
	  },
	  {
		"Name": "BlkBomb",
		"Element": "Fire",
		"MB": "32 MB",
		"ATK": "250",
		"Codes": "B F O",
		"Description": "Thrw shel 3sqr fwd. Fire attk",
		"Image": "https://vignette.wikia.nocookie.net/megaman/images/f/fc/BN6Chip065.png",
		"MoreDetails": "https://bit.ly/2XBDww8",
		"Alias": "BlackBomb"
	  },
	  {
		"Name": "BugBomb",
		"Element": "Null",
		"MB": "24 MB",
		"ATK": "0",
		"Codes": "G S V",
		"Description": "Throws a BugBomb 3sq ahead",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/fc/BN6Chip065.png",
		"MoreDetails": "https://bit.ly/2XykeHR",
	  },
	  {
		"Name": "GrasSeed",
		"Element": "Wood",
		"MB": "19 MB",
		"ATK": "0",
		"Codes": "A F S *",
		"Description": "Makes 9sq meadow 3sq ahead",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/bf/BN6Chip067.png",
		"MoreDetails": "https://bit.ly/32lJZtJ",
		"Alias": "GrassSeed"
	  },
	  {
		"Name": "IceSeed",
		"Element": "Aqua",
		"MB": "31 MB",
		"ATK": "0",
		"Codes": "A L R *",
		"Description": "Makes 9sq ice field 3sq ahead",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/6/65/BN6Chip068.png",
		"MoreDetails": "https://bit.ly/32lJZtJ",
	  },
	  {
		"Name": "PoisSeed",
		"Element": "None",
		"MB": "37 MB",
		"ATK": "0",
		"Codes": "H N P *",
		"Description": "Makes 9sq poisn swp 3sq ahead",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/81/BN6Chip069.png",
		"MoreDetails": "https://bit.ly/32lJZtJ",
		"Alias": "PoisonSeed"
	  },
	  {
		"Name": "Sword",
		"Element": "Sword",
		"MB": "8 MB",
		"ATK": "80",
		"Codes": "H L S *",
		"Description": "Cuts enmy in front! Range: 1",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/7/70/BN6Chip070.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "WideSwrd",
		"Element": "Sword",
		"MB": "12 MB",
		"ATK": "80",
		"Codes": "H L S *",
		"Description": "Cuts enmy in front! Range: 3",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a6/BN6Chip071.png",
		"MoreDetails": "",
		"Alias": "WideSword"
	  },
	  {
		"Name": "LongSwrd",
		"Element": "Sword",
		"MB": "25 MB",
		"ATK": "100",
		"Codes": "H L S *",
		"Description": "Cuts enmy in front! Range: 2",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/60/BN6Chip072.png",
		"MoreDetails": "",
		"Alias": "LongSword"
	  },
	  {
		"Name": "WideBlde",
		"Element": "Sword",
		"MB": "38 MB",
		"ATK": "150",
		"Codes": "B R W",
		"Description": "Cuts enmy in front! Range: 3",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/13/BN6Chip073.png",
		"MoreDetails": "",
		"Alias": "WideBlade"
	  },
	  {
		"Name": "LongBlde",
		"Element": "Sword",
		"MB": "38 MB",
		"ATK": "150",
		"Codes": "B M V",
		"Description": "Cuts enmy in front! Range: 2",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/37/BN6Chip074.png",
		"MoreDetails": "",
		"Alias": "LongBlade"
	  },
	  {
		"Name": "FireSwrd",
		"Element": "Fire",
		"MB": "30 MB",
		"ATK": "140",
		"Codes": "F O Z",
		"Description": "Cut enmy 3sq fwrd w/fire",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/bd/BN6Chip075.png",
		"MoreDetails": "",
		"Alias": "FireSword"
	  },
	  {
		"Name": "AquaSwrd",
		"Element": "Aqua",
		"MB": "32 MB",
		"ATK": "160",
		"Codes": "A I Y",
		"Description": "Cut enmy 3sq fwrd w/aqua",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/32/BN6Chip076.png",
		"MoreDetails": "",
		"Alias": "AquaSword"
	  },
	  {
		"Name": "ElecSwrd",
		"Element": "Elec",
		"MB": "32 MB",
		"ATK": "120",
		"Codes": "E K N",
		"Description": "Cut enmy 3sq fwrd w/elec",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/4/44/BN6Chip077.png",
		"MoreDetails": "",
		"Alias": "ElecSword"
	  },
	  {
		"Name": "BambSwrd",
		"Element": "Wood",
		"MB": "34 MB",
		"ATK": "150",
		"Codes": "H S W",
		"Description": "Cut enmy 3sq fwrd w/wood",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/d/d7/BN6Chip078.png",
		"MoreDetails": "",
		"Alias": "BambooSword, BambSword"
	  },
	  {
		"Name": "WindRack",
		"Element": "Wind",
		"MB": "19 MB",
		"ATK": "140",
		"Codes": "F J R *",
		"Description": "Blow enmy in front! Range: 3",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/11/BN6Chip079.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "StepSwrd",
		"Element": "Sword",
		"MB": "28 MB",
		"ATK": "160",
		"Codes": "B L P",
		"Description": "Use WideSwrd 2sq ahead",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/b/b5/BN6Chip080.png",
		"MoreDetails": "",
		"Alias": "StepSword"
	  },
	  {
		"Name": "VarSwrd",
		"Element": "Sword",
		"MB": "28 MB",
		"ATK": "160",
		"Codes": "K V W",
		"Description": "A magical shifting sword.",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/3/37/BN6Chip081.png",
		"MoreDetails": "https://bit.ly/2T8hP0Q",
	  },
	  {
		"Name": "NeoVari",
		"Element": "Sword",
		"MB": "52 MB",
		"ATK": "220",
		"Codes": "N",
		"Description": "A magical shifting sword.",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/d/de/BN6Chip082.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "MoonBld",
		"Element": "Sword",
		"MB": "35 MB",
		"ATK": "130",
		"Codes": "A M T",
		"Description": "Slices enemies around",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/d/de/BN6Chip083.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Muramasa",
		"Element": "Sword",
		"MB": "77 MB",
		"ATK": "????",
		"Codes": "M",
		"Description": "Atk power equals amt of lostHP",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/bf/BN6Chip084.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "MchnSwrd",
		"Element": "Null",
		"MB": "37 MB",
		"ATK": "200",
		"Codes": "H L Q",
		"Description": "Search and hit stund enemies.",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/8/88/BN6Chip085.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElemSwrd",
		"Element": "Null",
		"MB": "43 MB",
		"ATK": "220",
		"Codes": "J M U",
		"Description": "Cuts enmy on grass, ice, fire",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/f/f2/BN6Chip086.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AssnSwrd",
		"Element": "Null",
		"MB": "50 MB",
		"ATK": "240",
		"Codes": "N R Y",
		"Description": "When plyz cut enemy spec panl",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/5/59/BN6Chip087.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CrakShot",
		"Element": "Null",
		"MB": "4 MB",
		"ATK": "60",
		"Codes": "A G T *",
		"Description": "Shoot a panel at an enemy!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2d/BN6Chip088.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DublShot",
		"Element": "Null",
		"MB": "8 MB",
		"ATK": "60",
		"Codes": "C R U *",
		"Description": "Shoot 2 panels at an enemy!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/ee/BN6Chip089.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TrplShot",
		"Element": "Null",
		"MB": "16 MB",
		"ATK": "100",
		"Codes": "J L V *",
		"Description": "Shoot 3 panels at an enemy!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/ba/BN6Chip090.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Reflectr1",
		"Element": "Null",
		"MB": "7 MB",
		"ATK": "60",
		"Codes": "A C P *",
		"Description": "Bounce an attk back at them!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/01/BN6Chip091.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Reflectr2",
		"Element": "Null",
		"MB": "16 MB",
		"ATK": "120",
		"Codes": "B G Y *",
		"Description": ""Bounce an attk back at them!,
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/c/c0/BN6Chip092.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Reflectr3",
		"Element": "Null",
		"MB": "25 MB",
		"ATK": "200",
		"Codes": "E F O *",
		"Description": "Bounce an attk back at them!",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/d/d9/BN6Chip093.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "WaveArm1",
		"Element": "Null",
		"MB": "15 MB",
		"ATK": "80",
		"Codes": "E F G",
		"Description": "Fllw enemy and fire trap wave",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/2f/BN6Chip094.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "WaveArm2",
		"Element": "Null",
		"MB": "22 MB",
		"ATK": "120",
		"Codes": "L M N",
		"Description": "llw enemy and fire trap wave",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/20/BN6Chip095.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "WaveArm3",
		"Element": "Null",
		"MB": "29 MB",
		"ATK": "160",
		"Codes": "R S T",
		"Description": "Fllw enemy and fire trap wave",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/a/a9/BN6Chip096.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SandWrm1",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "130",
		"Codes": "A G L",
		"Description": "Attk enmy from rear w/snakarm",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a8/BN6Chip097.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SandWrm2",
		"Element": "Null",
		"MB": "34 MB",
		"ATK": "150",
		"Codes": "B R Y",
		"Description": "Attk enmy from rear w/snakearm",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/2/2c/BN6Chip098.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SandWrm3",
		"Element": "Null",
		"MB": "38 MB",
		"ATK": "170",
		"Codes": "H J S",
		"Description": "Attk enmy from rear w/snakearm",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/f2/BN6Chip099.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SumnBlk1",
		"Element": "Null(Secondary: Sword)",
		"MB": "30 MB",
		"ATK": "160",
		"Codes": "E I P",
		"Description": "Summon a Nghtmare attack!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/8/82/BN6Chip100.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SumnBlk2",
		"Element": "Null",
		"MB": "40 MB",
		"ATK": "200",
		"Codes": "H O V",
		"Description": "Summon a Nghtmare attack!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/28/BN6Chip101.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SumnBlk3",
		"Element": "Null",
		"MB": "46 MB",
		"ATK": "260",
		"Codes": "W Y Z",
		"Description": "Summon a Nghtmare attack!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/a6/BN6Chip102.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Snake",
		"Element": "Null",
		"MB": "34 MB",
		"ATK": "30",
		"Codes": "H L M",
		"Description": "Call snke from hole in area.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/84/BN6Chip103.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "NumbrBl",
		"Element": "Null",
		"MB": "69 MB",
		"ATK": "????",
		"Codes": "N",
		"Description": "Last 2 HP digits = atk pwr",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/3/31/BN6Chip104.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "FireHit1",
		"Element": "Fire",
		"MB": "12 MB",
		"ATK": "60",
		"Codes": "D E F",
		"Description": "Slams closest enemy",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/9/95/BN6Chip105.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "FireHit2",
		"Element": "Fire",
		"MB": "22 MB",
		"ATK": "120",
		"Codes": "R S T",
		"Description": "Slams closest enemy",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/e4/BN6Chip106.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "FireHit3",
		"Element": "Fire",
		"MB": "32 MB",
		"ATK": "180",
		"Codes": "A B C",
		"Description": "Slams closest enemy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/f8/BN6Chip107.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BurnSqr1",
		"Element": "Fire",
		"MB": "24 MB",
		"ATK": "100",
		"Codes": "H P V",
		"Description": "Press A to burn a 4pnl sqr",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/a/a7/BN6Chip108.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BurnSqr2",
		"Element": "Fire",
		"MB": "30 MB",
		"ATK": "120",
		"Codes": "D M T",
		"Description": "Press A to burn a 4pnl sqr",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/b/bb/BN6Chip109.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BurnSqr3",
		"Element": "Fire",
		"MB": "36 MB",
		"ATK": "140",
		"Codes": "E O Z",
		"Description": "Press A to burn a 4pnl sqr",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/bf/BN6Chip110.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Meteors",
		"Element": "Fire",
		"MB": "73 MB",
		"ATK": "40",
		"Codes": "R",
		"Description": "Drop many meteor on enmy area",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/fe/BN6Chip111.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AquaNdl1",
		"Element": "Aqua",
		"MB": "31 MB",
		"ATK": "40",
		"Codes": "C J P",
		"Description": "Target 3 needles at enemy!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/9/9a/BN6Chip112.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AquaNdl2",
		"Element": "Aqua",
		"MB": "35 MB",
		"ATK": "60",
		"Codes": "F K T",
		"Description": "Target 3 needles at enemy!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/1/18/BN6Chip113.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AquaNdl3",
		"Element": "Aqua",
		"MB": "39 MB",
		"ATK": "80",
		"Codes": "A L U",
		"Description": "Target 3 needles at enemy!",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/80/BN6Chip114.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BlzrdBal",
		"Element": "Aqua",
		"MB": "39 MB",
		"ATK": "150",
		"Codes": "H N T",
		"Description": "Launch a giant snowball",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/c/c0/BN6Chip115.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Sensor1",
		"Element": "Elec",
		"MB": "32 MB",
		"ATK": "100",
		"Codes": "J O W",
		"Description": "Hit enmy with beam from snsr",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/f1/BN6Chip116.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Sensor2",
		"Element": "Elec",
		"MB": "35 MB",
		"ATK": "130",
		"Codes": "N U Y",
		"Description": "Hit enmy with beam from snsr",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/0/0d/BN6Chip117.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Sensor3",
		"Element": "Elec",
		"MB": "38 MB",
		"ATK": "160",
		"Codes": "I K Q",
		"Description": "Hit enmy with beam from snsr",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/ab/BN6Chip118.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Boomer",
		"Element": "Wood",
		"MB": "16 MB",
		"ATK": "100",
		"Codes": "J K T",
		"Description": "Boomerang that circ btl field",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/14/BN6Chip119.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HiBoomer",
		"Element": "Wood",
		"MB": "26 MB",
		"ATK": "140",
		"Codes": "B L V",
		"Description": "Boomerang that circ btl field",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/9/99/BN6Chip120.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "M-Boomer",
		"Element": "Wood",
		"MB": "36 MB",
		"ATK": "170",
		"Codes": "I M W",
		"Description": "Boomerang that circ btl field",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/67/BN6Chip121.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Lance",
		"Element": "Wood",
		"MB": "42 MB",
		"ATK": "150",
		"Codes": "A R W *",
		"Description": "Lance through back line",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/b/b7/BN6Chip122.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HeatDrgn",
		"Element": "Fire",
		"MB": "40 MB",
		"ATK": "140",
		"Codes": "G R T",
		"Description": "Drgn near clst enmy Hit 2 rows",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/a5/BN6Chip123.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElecDrgn",
		"Element": "Elec",
		"MB": "40 MB",
		"ATK": "150",
		"Codes": "A L V",
		"Description": "Drgn near clst enmy Hit 2 rows",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/2/28/BN6Chip124.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AquaDrgn",
		"Element": "Aqua",
		"MB": "44 MB",
		"ATK": "120",
		"Codes": "H P S",
		"Description": "Drgn near clst enmy Hit 2 rows",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/a/a3/BN6Chip125.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "WoodDrgn",
		"Element": "Wood",
		"MB": "48 MB",
		"ATK": "130",
		"Codes": "G T V",
		"Description": "Drgn near clst enmy Hit 2 rows",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/a4/BN6Chip126.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GolmHit1",
		"Element": "Break",
		"MB": "17 MB",
		"ATK": "140",
		"Codes": "I K Y",
		"Description": "Hit 3pnl area arnd clst enmy",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/5/51/BN6Chip127.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GolmHit2",
		"Element": "Break",
		"MB": "27 MB",
		"ATK": "190",
		"Codes": "D P U",
		"Description": "Hit 3pnl area arnd clst enmy",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/3/33/BN6Chip128.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GolmHit3",
		"Element": "Break",
		"MB": "37 MB",
		"ATK": "250",
		"Codes": "H M V",
		"Description": "Hit 3pnl area arnd clst enmy",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/3/3c/BN6Chip129.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "JustcOne",
		"Element": "Break",
		"MB": "90 MB",
		"ATK": "220",
		"Codes": "J",
		"Description": "Fist Atk on center panel",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/ff/BN6Chip130.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AirSpin1",
		"Element": "Wind",
		"MB": "22 MB",
		"ATK": "50",
		"Codes": "F G R",
		"Description": "Spits out hurricane attack",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/7/74/BN6Chip131.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AirSpin2",
		"Element": "Wind",
		"MB": "29 MB",
		"ATK": "50",
		"Codes": "A L T",
		"Description": "Spits out hurricane attack",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/3/32/BN6Chip132.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AirSpin3",
		"Element": "Wind",
		"MB": "36 MB",
		"ATK": "50",
		"Codes": "N O T",
		"Description": "Spits out hurricane attack",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/24/BN6Chip133.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Wind",
		"Element": "Wind",
		"MB": "10 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Windbox blows at enmy area",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/12/BN6Chip134.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Fan",
		"Element": "Wind",
		"MB": "10 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "VacuumFn pulls enemy in",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/d/df/BN6Chip135.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Magnum",
		"Element": "Cursor",
		"MB": "31 MB",
		"ATK": "130",
		"Codes": "F L W",
		"Description": "Cursor destroys panels!",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/7/7e/BN6Chip136.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CircGun",
		"Element": "Cursor",
		"MB": "35 MB",
		"ATK": "150",
		"Codes": "P T V",
		"Description": "Stop sght w/Button and attck",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/9/9f/BN6Chip137.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "RockCube",
		"Element": "Summon",
		"MB": "6 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Place a RockCube in front",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/0b/BN6Chip138.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "LilBolr1",
		"Element": "Summon and Aqua",
		"MB": "18 MB",
		"ATK": "100",
		"Codes": "F K L",
		"Description": "3pnl fwd Kttl attk Attack+",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/c/c9/BN6Chip139.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "LilBolr2",
		"Element": "Summon and Aqua",
		"MB": "23 MB",
		"ATK": "140",
		"Codes": "E M V",
		"Description": "3pnl fwd Kttl attk Attack+",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/f5/BN6Chip140.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "LilBolr3",
		"Element": "Summon and Aqua",
		"MB": "28 MB",
		"ATK": "180",
		"Codes": "G S Z",
		"Description": "3pnl fwd Kttl attk Attack+",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/19/BN6Chip141.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AirRaid1",
		"Element": "Summon",
		"MB": "26 MB",
		"ATK": "10",
		"Codes": "G K R",
		"Description": "Attk enmy w/flying FgtrPlne.",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/0d/BN6Chip142.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AirRaid2",
		"Element": "Summon",
		"MB": "32 MB",
		"ATK": "10",
		"Codes": "O T Y",
		"Description": "Attk enmy w/flying FgtrPlne.",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/5/57/BN6Chip143.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AirRaid3",
		"Element": "Summon",
		"MB": "39 MB",
		"ATK": "10",
		"Codes": "N U Z",
		"Description": "Attk enmy w/flying FgtrPlne.",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/5/53/BN6Chip144.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TimeBom1",
		"Element": "Summon",
		"MB": "20 MB",
		"ATK": "150",
		"Codes": "F G H",
		"Description": "Explodes 3 seconds later",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/3/3e/BN6Chip145.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TimeBom2",
		"Element": "Summon",
		"MB": "30 MB",
		"ATK": "190",
		"Codes": "C D E",
		"Description": "Explodes 3 seconds later",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/15/BN6Chip146.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TimeBom3",
		"Element": "Summon",
		"MB": "37 MB",
		"ATK": "230",
		"Codes": "L M N",
		"Description": "Explodes 3 seconds later",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/a/ae/BN6Chip147.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Mine",
		"Element": "Summon",
		"MB": "28 MB",
		"ATK": "200",
		"Codes": "A S T",
		"Description": "Place a mine in enmy area",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/e4/BN6Chip148.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Fanfare",
		"Element": "Summon",
		"MB": "20 MB",
		"ATK": "--",
		"Codes": "P S Z *",
		"Description": "Take no dmage for a while",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/61/BN6Chip149.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Discord",
		"Element": "Summon",
		"MB": "20 MB",
		"ATK": "--",
		"Codes": "A S G *",
		"Description": "Confuses enemies w/music",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/20/BN6Chip150.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Timpani",
		"Element": "Summon",
		"MB": "20 MB",
		"ATK": "--",
		"Codes": "I O T *",
		"Description": "Stop enmy feet with music",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/4/4f/BN6Chip151.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Silence",
		"Element": "Summon",
		"MB": "20 MB",
		"ATK": "--",
		"Codes": "B R W *",
		"Description": "Blinds enemies w/music",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b0/BN6Chip152.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "VDoll",
		"Element": "Summon",
		"MB": "39 MB",
		"ATK": "--",
		"Codes": "F N S *",
		"Description": "Throws VDoll 3sq ahead",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/e8/BN6Chip153.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Guardian",
		"Element": "Summon",
		"MB": "64 MB",
		"ATK": "200",
		"Codes": "O",
		"Description": "Statue punishes when hit",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a7/BN6Chip154.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Anubis",
		"Element": "Summon",
		"MB": "86 MB",
		"ATK": "--",
		"Codes": "P",
		"Description": "Anubis poisons enemies",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/0/0d/BN6Chip155.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov10",
		"Element": "Null",
		"MB": "4 MB",
		"ATK": "--",
		"Codes": "A D L *",
		"Description": "Recovers 10HP",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/0/04/BN6Chip156.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov30",
		"Element": "Null",
		"MB": "12 MB",
		"ATK": "--",
		"Codes": "E L Q *",
		"Description": "Recovers 30HP",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/fb/BN6Chip157.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov50",
		"Element": "Null",
		"MB": "18 MB",
		"ATK": "--",
		"Codes": "C M P *",
		"Description": "Recovers 50HP",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/4/4f/BN6Chip158.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov80",
		"Element": "Null",
		"MB": "24 MB",
		"ATK": "--",
		"Codes": "H K V *",
		"Description": "Recovers 80HP",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/9/93/BN6Chip159.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov120",
		"Element": "Null",
		"MB": "32 MB",
		"ATK": "--",
		"Codes": "F P S",
		"Description": "Recovers 120HP",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/12/BN6Chip160.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov150",
		"Element": "Null",
		"MB": "36 MB",
		"ATK": "--",
		"Codes": "J M T",
		"Description": "Recovers 150HP",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/f/fa/BN6Chip161.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov200",
		"Element": "Null",
		"MB": "42 MB",
		"ATK": "--",
		"Codes": "I Q Z",
		"Description": "Recovers 200HP",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/9/9a/BN6Chip162.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Recov300",
		"Element": "Null",
		"MB": "48 MB",
		"ATK": "--",
		"Codes": "J O Y",
		"Description": "Recovers 300HP",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/2/21/BN6Chip163.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "PanlGrab",
		"Element": "Null",
		"MB": "6 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Steals 1 enemy square!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/e/e1/BN6Chip164.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AreaGrab",
		"Element": "Null",
		"MB": "8 MB",
		"ATK": "--",
		"Codes": "B F S *",
		"Description": "Steals left edge from enmy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/7/7d/BN6Chip165.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GrabBnsh",
		"Element": "Null",
		"MB": "24 MB",
		"ATK": "--",
		"Codes": "B M S",
		"Description": "20 damage for every stolen sq",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2b/BN6Chip166.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GrabRvng",
		"Element": "Null",
		"MB": "50 MB",
		"ATK": "--",
		"Codes": "I Q Z",
		"Description": "40 damage for every stolen sq",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/4/44/BN6Chip167.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "PnlRetrn",
		"Element": "Null",
		"MB": "14 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Fix your area's panels",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/39/BN6Chip168.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Geddon",
		"Element": "Null",
		"MB": "47 MB",
		"ATK": "--",
		"Codes": "A L R *",
		"Description": "Breaks all empty panels",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/4/44/BN6Chip169.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HolyPanl",
		"Element": "Null",
		"MB": "24 MB",
		"ATK": "--",
		"Codes": "A B S *",
		"Description": "Creates a HolyPanl in front",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/f/f3/BN6Chip170.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Snctuary",
		"Element": "Null",
		"MB": "62 MB",
		"ATK": "--",
		"Codes": "Z",
		"Description": "Chng all own panel to holy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/83/BN6Chip171.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ComingRd",
		"Element": "Null",
		"MB": "21 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Pull an enemy to the front",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/3/38/BN6Chip172.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GoingRd",
		"Element": "Null",
		"MB": "21 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Push an enemy to the back",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/ba/BN6Chip173.png",
		"MoreDetails": "",
	  },
	  {
		"Name": SloGauge"",
		"Element": "Null",
		"MB": "42 MB",
		"ATK": "--",
		"Codes": "A B G *",
		"Description": "CustGauge slow-down",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/ed/BN6Chip174.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "FstGauge",
		"Element": "Null",
		"MB": "48 MB",
		"ATK": "--",
		"Codes": "E M R *",
		"Description": "CustGauge speed-up",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/5/57/BN6Chip175.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "FullCust",
		"Element": "Null",
		"MB": "50 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "CustGauge instantly refills",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/0/00/BN6Chip176.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BusterUp",
		"Element": "Null",
		"MB": "11 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Power goes up by 1",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/4/48/BN6Chip177.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BugFix",
		"Element": "Null",
		"MB": "62 MB",
		"ATK": "--",
		"Codes": "K P Z *",
		"Description": "Repairs and removes bugs",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/4/4a/BN6Chip178.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Invisibl",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Invisible for a while",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/bb/BN6Chip179.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Barrier",
		"Element": "Null",
		"MB": "7 MB",
		"ATK": "--",
		"Codes": "A F R *",
		"Description": "Nullifies 10 HP of damage",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/a/ab/BN6Chip180.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Barr100",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "--",
		"Codes": "H O Y",
		"Description": "Nullifies 100 HP of damage",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/bb/BN6Chip181.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Barr200",
		"Element": "Null",
		"MB": "52 MB",
		"ATK": "--",
		"Codes": "K U W",
		"Description": "Nullifies 200 HP of damage",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/4/4b/BN6Chip182.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BblWrap",
		"Element": "Aqua",
		"MB": "58 MB",
		"ATK": "--",
		"Codes": "I Q Z",
		"Description": "Weak against elec atk",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b9/BN6Chip183.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "LifeAur",
		"Element": "Null",
		"MB": "70 MB",
		"ATK": "--",
		"Codes": "U",
		"Description": "Repel all attacks under200",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/ba/BN6Chip184.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "MagCoil",
		"Element": "Null",
		"MB": "14 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Draw in enmy with mag force",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/3a/BN6Chip185.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ColArmy",
		"Element": "Null",
		"MB": "25 MB",
		"ATK": "40",
		"Codes": "B G R *",
		"Description": "Launch an attk with Col. army",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/68/BN6Chip186.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElemTrap",
		"Element": "Null",
		"MB": "42 MB",
		"ATK": "240",
		"Codes": "G S U *",
		"Description": "Trap enmy and attk with elem",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/b/b9/BN6Chip187.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AntiNavi",
		"Element": "Null",
		"MB": "50 MB",
		"ATK": "--",
		"Codes": "F L T *",
		"Description": "Takes the enemy's Navi away",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/2/2b/BN6Chip188.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AntiDmg",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "100",
		"Codes": "G R V *",
		"Description": "Sets trap and throw stars",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/aa/BN6Chip189.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AntiSword",
		"Element": "Null",
		"MB": "33 MB",
		"ATK": "100",
		"Codes": "A R Z *",
		"Description": "Retaliate for sword damage",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/08/BN6Chip190.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "AntiRecov",
		"Element": "Null",
		"MB": "37 MB",
		"ATK": "--",
		"Codes": "A F V *",
		"Description": "Damages enemy in recovery",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/8c/BN6Chip191.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "WhiCapsl",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Add an effect: Paralyze",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/0/03/BN6Chip192.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Uninstll",
		"Element": "Null",
		"MB": "60 MB",
		"ATK": "--",
		"Codes": "G L R",
		"Description": "Attach to NoDim Chp NavCusOff",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/9/96/BN6Chip193.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CopyDmg",
		"Element": "Null",
		"MB": "12 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Duplicate damage to 2nd enemy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/9/9c/BN6Chip194.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "LifeSync",
		"Element": "Cursor",
		"MB": "12 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "Makes HP same as enemy",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/2/2a/BN6Chip195.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Atk+10",
		"Element": "Bonus Point",
		"MB": "4 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "+10 for selected atk chip",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/1f/BN6Chip196.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Atk+30",
		"Element": "Bonus Point",
		"MB": "66 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "+30 for selected atk chip",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/f5/BN6Chip197.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Navi+20",
		"Element": "Bonus Point",
		"MB": "36 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "+20 for selected Navi chip",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/6/6a/BN6Chip198.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ColorPt",
		"Element": "Bonus Point",
		"MB": "31 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "+10 for next chip attack",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/d/d9/BN6Chip199.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DblPoint",
		"Element": "Bonus Point",
		"MB": "50 MB",
		"ATK": "--",
		"Codes": "*",
		"Description": "+20 for next chip attack",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/c/c5/BN6Chip200.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GunDelEX",
		"Element": "Null",
		"MB": "80 MB",
		"ATK": "--",
		"Codes": "G",
		"Description": "EXE6 Only. Fires a spread sunbeam",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/e9/BN5TCSChip020.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Otenko",
		"Element": "Summon",
		"MB": "66 MB",
		"ATK": "--",
		"Codes": "O",
		"Description": "EXE6 Only. Put Otnko to raise atk pwr",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/7/7e/BN5TCSChip019.png",
		"MoreDetails": "",
	  }
	}
	"Mega": {
	  {
		"Name": "Roll",
		"Element": "Null",
		"MB": "20 MB",
		"ATK": "20",
		"Codes": "R *",
		"Description": "Attacks enmy, then heals you",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/6/65/BN6MChip001.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Roll2",
		"Element": "Null",
		"MB": "40 MB",
		"ATK": "40",
		"Codes": "R",
		"Description": "Attacks enmy, then heals you",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/4/48/BN6MChip002.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Roll3",
		"Element": "Null",
		"MB": "60 MB",
		"ATK": "60",
		"Codes": "R",
		"Description": "Attacks enmy, then heals you",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/e5/BN6MChip003.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ProtoMan",
		"Element": "Sword",
		"MB": "41",
		"ATK": "150",
		"Codes": "B *",
		"Description": "Move in and slice the enemy. The worse BN5 version.",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/7/7a/BN6MChip004.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ProtoManEX",
		"Element": "Sword",
		"MB": "53",
		"ATK": "170",
		"Codes": "B",
		"Description": "Move in and slice the enemy.",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/6/60/BN6MChip005.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ProtoManSP",
		"Element": "Sword",
		"MB": "68 MB",
		"ATK": "290",
		"Codes": "B",
		"Description": "Move in and slice the enemy.",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/19/BN6MChip006.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SpoutMan",
		"Element": "Aqua",
		"MB": "42 MB",
		"ATK": "50",
		"Codes": "A *",
		"Description": "Watr atk! Bhnd 2row power-up",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/4/41/BN6FMChip007.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SpoutMnEX",
		"Element": "Aqua",
		"MB": "56 MB",
		"ATK": "60",
		"Codes": "A",
		"Description": "Watr atk! Bhnd 2row power-up",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/17/BN6FMChip008.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SpoutMnSP",
		"Element": "Aqua",
		"MB": "78 MB",
		"ATK": "120",
		"Codes": "A",
		"Description": "Watr atk! Bhnd 2row power-up",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/c/c7/BN6FMChip009.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TmhkMan",
		"Element": "Wood",
		"MB": "40 MB",
		"ATK": "140",
		"Codes": "T *",
		"Description": "Slice 2sq side, 3sq vertical",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/2/27/BN6FMChip010.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TmhkManEX",
		"Element": "Wood",
		"MB": "60 MB",
		"ATK": "160",
		"Codes": "T",
		"Description": "Slice 2sq side, 3sq vertical",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/80/BN6FMChip011.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TmhkManSP",
		"Element": "Wood",
		"MB": "80 MB",
		"ATK": "280",
		"Codes": "T",
		"Description": "Slice 2sq side, 3sq vertical",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/7/7c/BN6FMChip012.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TenguMan",
		"Element": "Wind",
		"MB": "43 MB",
		"ATK": "70",
		"Codes": "T *",
		"Description": "Attk 2row from air, then side",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/8/83/BN6FMChip013.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TenguMnEX",
		"Element": "Wind",
		"MB": "61 MB",
		"ATK": "90",
		"Codes": "T",
		"Description": "Attk 2row from air, then side",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/b3/BN6FMChip014.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "TenguMnSP",
		"Element": "Wind",
		"MB": "74 MB",
		"ATK": "160",
		"Codes": "T",
		"Description": "Attk 2row from air, then side",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/fe/BN6FMChip015.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GrndMan",
		"Element": "Break",
		"MB": "41 MB",
		"ATK": "60",
		"Codes": "G *",
		"Description": "Move fwrd then attk w/ drill",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/ef/BN6FMChip016.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GrndManEX",
		"Element": "Break",
		"MB": "66 MB",
		"ATK": "70",
		"Codes": "G",
		"Description": "Move fwrd then attk w/ drill",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2d/BN6FMChip017.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "GrndManSP",
		"Element": "Break",
		"MB": "85 MB",
		"ATK": "130",
		"Codes": "G",
		"Description": "Move fwrd then attk w/ drill",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a0/BN6FMChip018.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DustMan",
		"Element": "Null",
		"MB": "39 MB",
		"ATK": "110",
		"Codes": "D *",
		"Description": "Attk ahd. Suck in and shoot out",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/0b/BN6FMChip019.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DustManEX",
		"Element": "Null",
		"MB": "56 MB",
		"ATK": "130",
		"Codes": "D",
		"Description": "Attk ahd. Suck in and shoot out",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/8/8f/BN6FMChip020.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DustManSP",
		"Element": "Null",
		"MB": "74 MB",
		"ATK": "200",
		"Codes": "D",
		"Description": "Attk ahd. Suck in and shoot out",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/14/BN6FMChip021.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HeatMan",
		"Element": "Fire",
		"MB": "32 MB",
		"ATK": "100",
		"Codes": "H *",
		"Description": "Burn with a radial fire attk",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/3c/BN6GMChip007.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HeatManEX",
		"Element": "Fire",
		"MB": "55 MB",
		"ATK": "130",
		"Codes": "H",
		"Description": "Burn with a radial fire attk",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/3/3c/BN6GMChip008.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HeatManSP",
		"Element": "Fire",
		"MB": "70 MB",
		"ATK": "260",
		"Codes": "H",
		"Description": "Burn with a radial fire attk",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/fe/BN6GMChip009.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElecMan",
		"Element": "Elec",
		"MB": "38 MB",
		"ATK": "120",
		"Codes": "E *",
		"Description": "Attk your surrndns with thdr",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/f0/BN6GMChip010.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElecManEX",
		"Element": "Elec",
		"MB": "52 MB",
		"ATK": "140",
		"Codes": "E",
		"Description": "Attk your surrndns with thdr",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b8/BN6GMChip011.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElecManSP",
		"Element": "Elec",
		"MB": "79 MB",
		"ATK": "210",
		"Codes": "E",
		"Description": "Attk your surrndns with thdr",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/4/46/BN6GMChip012.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SlashMan",
		"Element": "Sword",
		"MB": "42 MB",
		"ATK": "80",
		"Codes": "S *",
		"Description": "Slash an enmy w/ flyn knfe",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/0f/BN6GMChip013.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SlashMnEX",
		"Element": "Sword",
		"MB": "65 MB",
		"ATK": "100",
		"Codes": "S",
		"Description": "Slash an enmy w/ flyn knfe",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/87/BN6GMChip014.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "SlashMnSP",
		"Element": "Sword",
		"MB": "79 MB",
		"ATK": "220",
		"Codes": "S",
		"Description": "Slash an enmy w/ flyn knfe",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/05/BN6GMChip015.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "EraseMan",
		"Element": "Cursor",
		"MB": "51 MB",
		"ATK": "120",
		"Codes": "K *",
		"Description": "Press (A) for 3panl beam attk",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/8/8b/BN6GMChip016.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "EraseMnEX",
		"Element": "Cursor",
		"MB": "65 MB",
		"ATK": "140",
		"Codes": "K",
		"Description": "Press (A) for 3panl beam attk",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/1f/BN6GMChip017.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "EraseMnSP",
		"Element": "Cursor",
		"MB": "79 MB",
		"ATK": "210",
		"Codes": "K",
		"Description": "Press (A) for 3panl beam attk",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/c/c8/BN6GMChip018.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ChrgeMan",
		"Element": "Null",
		"MB": "42",
		"ATK": "60",
		"Codes": "C *",
		"Description": "Rush fwd! Open panl hit TrCar",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/6e/BN6GMChip019.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ChrgeMnEX",
		"Element": "Null",
		"MB": "63 MB",
		"ATK": "70",
		"Codes": "C",
		"Description": "Rush fwd! Open panl hit TrCar",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/d/d1/BN6GMChip020.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ChrgeMnSP",
		"Element": "Null",
		"MB": "81 MB",
		"ATK": "130",
		"Codes": "C",
		"Description": "Rush fwd! Open panl hit TrCar",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/5/56/BN6GMChip021.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BlastMan",
		"Element": "Fire",
		"MB": "30 MB",
		"ATK": "120",
		"Codes": "B *",
		"Description": "Head fwd and launch blst attk",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/e6/BN6MChip022.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BlastMnEX",
		"Element": "Fire",
		"MB": "49 MB",
		"ATK": "140",
		"Codes": "B",
		"Description": "Head fwd and launch blst attk",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/0d/BN6MChip023.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BlastMnSP",
		"Element": "Fire",
		"MB": "68 MB",
		"ATK": "250",
		"Codes": "B",
		"Description": "Head fwd and launch blst attk",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/9/9c/BN6MChip024.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DiveMan",
		"Element": "Aqua",
		"MB": "45 MB",
		"ATK": "130",
		"Codes": "D *",
		"Description": "Snd giant wave acrs area 2pnl",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/e0/BN6MChip025.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DiveManEX",
		"Element": "Aqua",
		"MB": "60 MB",
		"ATK": "150",
		"Codes": "D",
		"Description": "Snd giant wave acrs area 2pnl",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/c/cc/BN6MChip026.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DiveManSP",
		"Element": "Aqua",
		"MB": "75 MB",
		"ATK": "270",
		"Codes": "D",
		"Description": "Snd giant wave acrs area 2pnl",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/a6/BN6MChip027.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CrcusMan",
		"Element": "Null",
		"MB": "42 MB",
		"ATK": "20",
		"Codes": "C *",
		"Description": "Capture enmy in a ash attck",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/6a/BN6MChip028.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CrcusMnEX",
		"Element": "Null",
		"MB": "64 MB",
		"ATK": "25",
		"Codes": "C",
		"Description": "Capture enmy in a ash attck",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/5/54/BN6MChip029.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CrcusMnSP",
		"Element": "Null",
		"MB": "86 MB",
		"ATK": "55",
		"Codes": "C",
		"Description": "Capture enmy in a ash attck",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/67/BN6MChip030.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "JudgeMan",
		"Element": "Elec",
		"MB": "52 MB",
		"ATK": "100",
		"Codes": "J *",
		"Description": "Whip 3 panels forward",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/1/10/BN6MChip031.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "JudgeMnEX",
		"Element": "Elec",
		"MB": "62 MB",
		"ATK": "120",
		"Codes": "J",
		"Description": "Whip 3 panels forward",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/8/89/BN6MChip032.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "JudgeMnSP",
		"Element": "Elec",
		"MB": "72 MB",
		"ATK": "190",
		"Codes": "J",
		"Description": "Whip 3 panels forward",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/f3/BN6MChip033.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElmntMan",
		"Element": "Null",
		"MB": "50 MB",
		"ATK": "100",
		"Codes": "E *",
		"Description": "Hit (A) whn col chges elem attk",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/83/BN6MChip034.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElmntMnEX",
		"Element": "Null",
		"MB": "53 MB",
		"ATK": "120",
		"Codes": "E",
		"Description": "Hit (A) whn col chges elem attk",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/5/54/BN6MChip035.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ElmntMnSP",
		"Element": "Null",
		"MB": "66 MB",
		"ATK": "240",
		"Codes": "E",
		"Description": "Hit (A) whn col chges elem attk",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/18/BN6MChip036.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Colonel",
		"Element": "Sword",
		"MB": "45 MB",
		"ATK": "160",
		"Codes": "C *",
		"Description": "Cut enmy lines in Z shape",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/ee/BN6MChip037.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ColonelEX",
		"Element": "Sword",
		"MB": "70 MB",
		"ATK": "180",
		"Codes": "C",
		"Description": "Cut enmy lines in Z shape",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/0b/BN6MChip038.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ColonelSP",
		"Element": "Sword",
		"MB": "91 MB",
		"ATK": "300",
		"Codes": "C",
		"Description": "Cut enmy lines in Z shape",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/4/49/BN6MChip039.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Count",
		"Element": "Null",
		"MB": "60 MB",
		"ATK": "20",
		"Codes": "H *",
		"Description": "EXE6 Only. Rain on enmy then lance atk",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/b/b8/BN6MJChip040.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CountEX",
		"Element": "Null",
		"MB": "75 MB",
		"ATK": "25",
		"Codes": "H",
		"Description": "EXE6 Only. Rain on enmy then lance atk",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a8/BN6MJChip041.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CountSP",
		"Element": "Null",
		"MB": "89 MB",
		"ATK": "50",
		"Codes": "H",
		"Description": "EXE6 Only. Rain on enmy then lance atk",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2a/BN6MJChip042.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Django",
		"Element": "Null",
		"MB": "30 MB",
		"ATK": "130",
		"Codes": "D *",
		"Description": "EXE6 Only. Hit enmy with bike rdng Djgo",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/eb/BN6MJChip043.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Django2",
		"Element": "Null",
		"MB": "70 MB",
		"ATK": "180",
		"Codes": "D",
		"Description": "EXE6 Only. Hit enmy with bike rdng Djgo",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/5/55/BN6MJChip044.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Django3",
		"Element": "Null",
		"MB": "90 MB",
		"ATK": "260",
		"Codes": "D",
		"Description": "EXE6 Only. Hit enmy with bike rdng Djgo",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b1/BN6MJChip045.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DblBeast",
		"Element": "Null",
		"MB": "99 MB",
		"ATK": "320",
		"Codes": "W",
		"Description": "EXE6 Only. Fang and wing doubl atk frenzy! ",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/9/9a/BN6GJ_DoubleBeast.png",
		"MoreDetails": "",
	  }
	}
	"Giga": {
	  {
		"Name": "Bass",
		"Element": "Null",
		"MB": "95 MB",
		"ATK": "60",
		"Codes": "F",
		"Description": "Gregar Only. Buster rake wide enmy area",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/0/0d/BN6GGChip001.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BigHook",
		"Element": "Break",
		"MB": "92 MB",
		"ATK": "240",
		"Codes": "H",
		"Description": "Gregar Only. Hook atk 2 sq wide",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/3/34/BN6GGChip002.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "DeltaRay",
		"Element": "Sword",
		"MB": "82 MB",
		"ATK": "260",
		"Codes": "Z",
		"Description": "Gregar Only. A button power up by 3 swrd",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/09/BN6GGChip003.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "ColForce",
		"Element": "Null",
		"MB": "90 MB",
		"ATK": "30",
		"Codes": "Q",
		"Description": "Gregar Only. Smn Col. army in open pnls.",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/25/BN6GGChip004.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BugRSwrd",
		"Element": "Sword",
		"MB": "80 MB",
		"ATK": "--",
		"Codes": "V",
		"Description": "Gregar Only. Use Bug Frag with DrkSword!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/7/75/BN6GGChip005.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BassAnly",
		"Element": "Null",
		"MB": "95 MB",
		"ATK": "160",
		"Codes": "F",
		"Description": "Falzar Only. A ring that hits 4 times",
		"Image": "https://vignette1.wikia.nocookie.net/megaman/images/9/91/BN6FGChip001.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "MetrKnuk",
		"Element": "Break",
		"MB": "90 MB",
		"ATK": "100",
		"Codes": "N",
		"Description": "Falzar Only. Meteors bombard from sky",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/7/7a/BN6FGChip002.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "CrossDiv",
		"Element": "Sword",
		"MB": "93 MB",
		"ATK": "250",
		"Codes": "D",
		"Description": "Falzar Only. Cross-slice!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/f7/BN6FGChip003.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "HubBatc",
		"Element": "Null",
		"MB": "99 MB",
		"ATK": "--",
		"Codes": "J",
		"Description": "Falzar Only. Blend Hub DNA Data w/MegaMan",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/f9/BN6FGChip004.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "BgDthThd",
		"Element": "Elec",
		"MB": "80 MB",
		"ATK": "--",
		"Codes": "V",
		"Description": "Falzar Only. Use Bug Frag with DarkThnd!",
		"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/e5/BN6FGChip005.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Gregar",
		"Element": "Null",
		"MB": "99 MB",
		"ATK": "300",
		"Codes": "X",
		"Description": "EXE6 Gregar Only. Gregar's scorching breath!",
		"Image": "https://vignette2.wikia.nocookie.net/megaman/images/b/be/BN6FGChip006.png",
		"MoreDetails": "",
	  },
	  {
		"Name": "Falzar",
		"Element": "Null",
		"MB": "99 MB",
		"ATK": "100",
		"Codes": "X",
		"Description": "EXE6 Falzar Only. Falzar's storming tornado!",
		"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/6a/BN6GGChip006.png",
		"MoreDetails": "",
	  }
	}
	"Program Advance": {
	  {
		"Name": "GigaCan1",
		"Combo": "Cannon A B C",
		"Element": "Null",
		"ATK": "300",
		"Description": "Giga lvl cannon attack!",
		"MoreDetails": "",
	  },
	  {
		"Name": "GigaCan2",
		"Combo": "HiCannon L M N",
		"Element": "Null",
		"ATK": "400",
		"Description": "Giga lvl cannon attack!",
		"MoreDetails": "",
	  },
	  {
		"Name": "GigaCan3",
		"Combo": "M-Cannon R S T",
		"Element": "Null",
		"ATK": "500",
		"Description": "Giga lvl cannon attack!",
		"MoreDetails": "",
	  },
	  {
		"Name": "WideBrn1",
		"Combo": "FireBrn1 F G H",
		"Element": "Fire",
		"ATK": "300",
		"Description": "An expnd 3 row fire attk",
		"MoreDetails": "",
	  },
	  {
		"Name": "WideBrn2",
		"Combo": "FireBrn2 S T U",
		"Element": "Fire",
		"ATK": "350",
		"Description": "An expnd 3 row fire attk",
		"MoreDetails": "",
	  },
	  {
		"Name": "WideBrn3",
		"Combo": "FireBrn3 C D E",
		"Element": "Fire",
		"ATK": "400",
		"Description": "An expnd 3 row fire attk",
		"MoreDetails": "",
	  },{
		"Name": "FlmHook1",
		"Combo": "FireHit1 D E F",
		"Element": "Fire",
		"ATK": "300",
		"Description": "Launch 2 flaming hooks!",
		"MoreDetails": "",
	  },
	  {
		"Name": "FlmHook2",
		"Combo": "FireHit2 R S T",
		"Element": "Fire",
		"ATK": "350",
		"Description": "Launch 2 flaming hooks!",
		"MoreDetails": "",
	  },{
		"Name": "FlmHook3",
		"Combo": "FireHit3 A B C",
		"Element": "Fire",
		"ATK": "400",
		"Description": "Launch 2 flaming hooks!",
		"MoreDetails": "",
	  },
	  {
		"Name": "PwrWave1",
		"Combo": "WaveArm1 E F G",
		"Element": "Null",
		"ATK": "400",
		"Description": "Send a pwrfl wav 3rows fwd",
		"MoreDetails": "",
	  },{
		"Name": "PwrWave2",
		"Combo": "WaveArm2 L M N",
		"Element": "Null",
		"ATK": "500",
		"Description": "Send a pwrfl wav 3rows fwd",
		"MoreDetails": "",
	  },
	  {
		"Name": "PwrWave3",
		"Combo": "WaveArm3 R S T",
		"Element": "Null",
		"ATK": "600",
		"Description": "Send a pwrfl wav 3rows fwd",
		"MoreDetails": "",
	  },{
		"Name": "CornFsta",
		"Combo": "CornSht1 J K L\r\nCornSht2 C D E\r\n\CornSht3 P Q R",
		"Element": "Wood",
		"ATK": "40",
		"Description": "Explosive corn with 9pnl rch!",
		"MoreDetails": "",
	  },
	  {
		"Name": "ParaShl",
		"Combo": "IronShl1 J K L\r\nIronShl2 C D E\r\n\IronShl3 L M N",
		"Element": "Null",
		"ATK": "350",
		"Description": "Shell atk on 5 rght grid rows",
		"MoreDetails": "",
	  },{
		"Name": "DestPuls",
		"Combo": "ElcPuls1 J ElcPuls2 J ElcPuls3 J",
		"Element": "Elec",
		"ATK": "400",
		"Description": "Fire puls that caus strg bug!",
		"MoreDetails": "",
	  },
	  {
		"Name": "Timebom+",
		"Combo": "TimeBom1 F G H\r\nTimeBom2 C D E\r\nTimeBom3 L M N",
		"Element": "Null",
		"ATK": "700",
		"Description": "Set TmBm+ in enemy area!",
		"MoreDetails": "",
	  },{
		"Name": "StreamHd",
		"Combo": "AuraHed1 B C D\r\nAuraHed2 D E F\r\n\AuraHed3 F G H",
		"Element": "Null",
		"ATK": "150",
		"Description": "Fire a strm of 5 AuraHeds",
		"MoreDetails": "",
	  },
	  {
		"Name": "SuprSpr",
		"Combo": "WideSht P Q R",
		"Element": "Aqua",
		"ATK": "150",
		"Description": "Fire 3 consec. WideShts",
		"MoreDetails": "",
	  },{
		"Name": "H-Burst",
		"Combo": "Spreadr1 L M N\r\nSpreadr2 A B C\r\n\Spreader3 Q R S",
		"Element": "Null",
		"ATK": "60",
		"Description": "Secondary explosion after hit",
		"MoreDetails": "",
	  },
	  {
		"Name": "LifeSrd",
		"Combo": "Sword * WideSwrd * LongSwrd *\r\nSword* WideBlde B LongBlde B",
		"Element": "Sword",
		"ATK": "400",
		"Description": "Slices 2sq wide 3sq vrtcl",
		"MoreDetails": "",
	  },{
		"Name": "GreatYo",
		"Combo": "YoYo L M N",
		"Element": "Sword",
		"ATK": "100",
		"Description": "Moves 3sq vertical",
		"MoreDetails": "",
	  },
	  {
		"Name": "PitHocky",
		"Combo": "AirHocky L M N",
		"Element": "Null",
		"ATK": "100",
		"Description": "Reflect hockey attack",
		"MoreDetails": "",
	  },{
		"Name": "PoisPhar",
		"Combo": "PoisSeed * x2 Anubis P",
		"Element": "Null",
		"ATK": "--",
		"Description": "Places a poisoned Pharaoh",
		"MoreDetails": "",
	  },
	  {
		"Name": "BodyGrd",
		"Combo": "AntiNavi * AntiSwrd * AntiDmg *",
		"Element": "Sword",
		"ATK": "100",
		"Description": "Trap enmy then thrw star attk",
		"MoreDetails": "",
	  },{
		"Name": "DblHero",
		"Combo": "WideBlde B LongBlde B ProtoMnSP B",
		"Element": "Null",
		"ATK": "60",
		"Description": "Attk with BtlNwk1's ProtoMan",
		"MoreDetails": "",
	  },
	  {
		"Name": "Darkness",
		"Combo": "VDoll * x2 Bass F\r\nVDoll * x2 BassAnly F",
		"Element": "Fire",
		"ATK": "300",
		"Description": "BtlNwk2's GspelBth & Bass Swrd",
		"MoreDetails": "",
	  },{
		"Name": "MstrCros",
		"Combo": "FireHit3 A AquaNdl3 A ElcPuls3 A RskyHny3 A",
		"Element": "Null",
		"ATK": "100",
		"Description": "Attk with all BN3's Cros Attk",
		"MoreDetails": "",
	  },
	  {
		"Name": "SunMoon",
		"Combo": "Meteors R Atk+30 * Uninstll R",
		"Element": "Fire",
		"ATK": "200",
		"Description": "Attk 3pnl fwd w/BN4 SunMn atk",
		"MoreDetails": "",
	  },{
		"Name": "TwinLdrs",
		"Combo": "ProtoMnSP B ANtiNavi * Colonel *\r\nColonelSP C AntiNavi * ProtoMan *",
		"Element": "Null",
		"ATK": "200",
		"Description": "Dbl attk w/BN5 Col and ProtM",
		"MoreDetails": "",
	  },
	  {
		"Name": "CrosOver",
		"Combo": "Django * Django2 D Django3 D",
		"Element": "Null",
		"ATK": "--",
		"Description": "Cllbrate! Attk w/MM + Django!",
		"MoreDetails": "",
	  }
	}
]