var GigaChips = [
{
	"Name": "Bass",
	"Element": "Null",
	"MB": "95 MB",
	"ATK": "60",
	"Codes": "F",
	"Description": "Gregar Only. Buster rake wide enmy area",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/0/0d/BN6GGChip001.png",
	"MoreDetails": "",
  },
  {
	"Name": "BigHook",
	"Element": "Break",
	"MB": "92 MB",
	"ATK": "240",
	"Codes": "H",
	"Description": "Gregar Only. Hook atk 2 sq wide",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/3/34/BN6GGChip002.png",
	"MoreDetails": "",
  },
  {
	"Name": "DeltaRay",
	"Element": "Sword",
	"MB": "82 MB",
	"ATK": "260",
	"Codes": "Z",
	"Description": "Gregar Only. A button power up by 3 swrd",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/09/BN6GGChip003.png",
	"MoreDetails": "",
  },
  {
	"Name": "ColForce",
	"Element": "Null",
	"MB": "90 MB",
	"ATK": "30",
	"Codes": "Q",
	"Description": "Gregar Only. Smn Col. army in open pnls.",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/25/BN6GGChip004.png",
	"MoreDetails": "",
  },
  {
	"Name": "BugRSwrd",
	"Element": "Sword",
	"MB": "80 MB",
	"ATK": "--",
	"Codes": "V",
	"Description": "Gregar Only. Use Bug Frag with DrkSword!",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/7/75/BN6GGChip005.png",
	"MoreDetails": "",
  },
  {
	"Name": "BassAnly",
	"Element": "Null",
	"MB": "95 MB",
	"ATK": "160",
	"Codes": "F",
	"Description": "Falzar Only. A ring that hits 4 times",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/9/91/BN6FGChip001.png",
	"MoreDetails": "",
  },
  {
	"Name": "MetrKnuk",
	"Element": "Break",
	"MB": "90 MB",
	"ATK": "100",
	"Codes": "N",
	"Description": "Falzar Only. Meteors bombard from sky",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/7/7a/BN6FGChip002.png",
	"MoreDetails": "",
  },
  {
	"Name": "CrossDiv",
	"Element": "Sword",
	"MB": "93 MB",
	"ATK": "250",
	"Codes": "D",
	"Description": "Falzar Only. Cross-slice!",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/f7/BN6FGChip003.png",
	"MoreDetails": "",
  },
  {
	"Name": "HubBatc",
	"Element": "Null",
	"MB": "99 MB",
	"ATK": "--",
	"Codes": "J",
	"Description": "Falzar Only. Blend Hub DNA Data w/MegaMan",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/f9/BN6FGChip004.png",
	"MoreDetails": "",
  },
  {
	"Name": "BgDthThd",
	"Element": "Elec",
	"MB": "80 MB",
	"ATK": "--",
	"Codes": "V",
	"Description": "Falzar Only. Use Bug Frag with DarkThnd!",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/e5/BN6FGChip005.png",
	"MoreDetails": "",
  },
  {
	"Name": "Gregar",
	"Element": "Null",
	"MB": "99 MB",
	"ATK": "300",
	"Codes": "X",
	"Description": "EXE6 Gregar Only. Gregar's scorching breath!",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/b/be/BN6FGChip006.png",
	"MoreDetails": "",
  },
  {
	"Name": "Falzar",
	"Element": "Null",
	"MB": "99 MB",
	"ATK": "100",
	"Codes": "X",
	"Description": "EXE6 Falzar Only. Falzar's storming tornado!",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/6a/BN6GGChip006.png",
	"MoreDetails": "",
  }
]